const chatForm = document.getElementById('chat-form');
const userInput = document.getElementById('user-input');
const chatWindow = document.getElementById('chat-window');
const newChat = document.getElementById('new-chat');
const exportChat = document.getElementById('export-chat');

let chatHistory = JSON.parse(localStorage.getItem('chatHistory')) || [];

function renderChat() {
  chatWindow.innerHTML = '';
  chatHistory.forEach(({ text, sender }) => {
    appendMessage(text, sender);
  });
}

function appendMessage(text, sender) {
  const messageEl = document.createElement('div');
  messageEl.classList.add('message', sender);

  const bubble = document.createElement('div');
  bubble.classList.add('bubble');

  if (sender === 'bot') {
    typeText(bubble, text);
  } else {
    bubble.innerText = text;
  }

  messageEl.appendChild(bubble);
  chatWindow.appendChild(messageEl);
  chatWindow.scrollTop = chatWindow.scrollHeight;
}

function addMessage(text, sender) {
  chatHistory.push({ text, sender });
  localStorage.setItem('chatHistory', JSON.stringify(chatHistory));
  appendMessage(text, sender);
}

chatForm.addEventListener('submit', (e) => {
  e.preventDefault();
  const input = userInput.value.trim();
  if (!input) return;

  addMessage(input, 'user');
  userInput.value = '';

  setTimeout(() => {
    fakeBotReply(input);
  }, 800);
});

function fakeBotReply(userText) {
  const reply = `🤖 You said: "${userText}"\nHere's a response generated by the bot.`;
  addMessage(reply, 'bot');
}

function typeText(element, text, i = 0) {
  if (i < text.length) {
    element.innerHTML += text.charAt(i);
    setTimeout(() => typeText(element, text, i + 1), 20);
  }
}

newChat.addEventListener('click', () => {
  chatHistory = [];
  localStorage.removeItem('chatHistory');
  renderChat();
});

exportChat.addEventListener('click', () => {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();
  let y = 10;

  doc.setFontSize(12);
  chatHistory.forEach(({ text, sender }) => {
    const label = sender === 'user' ? 'You:' : 'Bot:';
    const lines = doc.splitTextToSize(`${label} ${text}`, 180);

    if (y + lines.length * 7 > 280) {
      doc.addPage();
      y = 10;
    }

    lines.forEach(line => {
      doc.text(line, 10, y);
      y += 7;
    });

    y += 5;
  });

  doc.save('ChatGPT_Conversation.pdf');
});

window.addEventListener('load', renderChat);
